### ISSUE TITLE
not thread safe

### ISSUE THREAD

**Issue by jrochkind** [cbeer/devise-guests#12]
I don't actually use devise/devise-guests, but was reviewing the devise-guest code for ideas on how to upgrade to BL 3.7 in my non-devise app. 

I noticed this code:

```
    def unique_#{mapping}_counter
      @@unique_#{mapping}_counter ||= 0
      @@unique_#{mapping}_counter += 1
    end
```

https://github.com/cbeer/devise-guests/blob/master/lib/devise-guests/controllers/helpers.rb#L80

I wanted to point out that is not thread safe, for a Rails running under multi-threaded request dispatch. It uses global state, shared between requests, in the `@@unique_` variable, but does not synchronize access to this global state from requests, which may be running concurrently in different threads. 

Many Rails apps don't do concurrent request dispatching anyway. It requires an app server that can handle concurrent requests (passenger enterprise, puma, maybe a few others in unusual configurations). In Rails3 it also requires you to set `config.threadsafe!`, although in Rails4 that is on by default. 

So it might not matter that it's not thread-safe if hardly anyone runs Rails with concurrent request dispatch anyway, and I probably won't be using this gem myself anyway either, but thought I'd point it out since I noticed it, in case you are concerned.

**Comment by marcamillion** [comment]
Any progress on this? Was this ever fixed?
