### ISSUE TITLE
imcompabilities when using omniauth-facebook

### ISSUE THREAD

**Issue by ssoulless** [cbeer/devise-guests#18]
Hi, Just after I installed and configured this module I got a problem.

In my header I have this conditional

<% if current_or_guest_user.guest == false %>
show header for logged in users
<% else %>
show header for guest users (logged out users)
<% end %>

Well it worked normally before I installed this gem.

Now after I try to log in through facebook I get this error

undefined method `_logging_in_user_callbacks' 

Im trying to debug the issue but still no change, any idea?

**Comment by lacostenycoder** [comment]
Did anyone ever find a workaround or solution to this? I'm having the same issue.

**Comment by lacostenycoder** [comment]
This seemed to fix the problem.  Hopefully pull request will get merged.
https://github.com/davidkus/devise-guests

**Comment by pacso** [comment]
Closing as duplicate of #17
